### PR TITLE
Update utcDCtoMODS.xsl

### PR DESCRIPTION
**Pull request by carolynfrunyon**
Added 3 new sets for next DPLA harvest.

### CODE REVIEW

**Comment by CanOfBees** [comment]
@carolynfrunyon - thanks for the PR! I'm taking a look at this now.

**Comment by markpbaggett** [comment]
@CanOfBees / @carolynfrunyon , I'll take a look at this.  @CanOfBees, just so you know, we're going to move this repo out of our org since the IP really shouldn't sit with us.  We're still developing some work flows and documentation for that, so I apologize if this is confusing.

**Comment by markpbaggett** [comment]
@carolynfrunyon apologies.  Just getting around to looking at this now.  I've been traveling.  I'm going to:

1. Apply your change to repox.
2. Grab all your metadata.
3. Schema analyze it.

As long as no records are missing titleInfo/titles, accessConditions, or location/urls, we'll call it good.  Should have something within the hour.

**Comment by carolynfrunyon** [comment]
Sounds good! If there's something missing, let me know. And please don't worry about doing a bunch of analysis to figure out where it's missing. I can do that and make the fix. It's no problem.

**Comment by markpbaggett** [comment]
@carolynfrunyon one little problem. Line 221 has an un-escaped apostrophe hanging out. Do you mind addressing this and pushing up your change?  You don't have to open another pull request or close this one.  Since the p.r. is open, it will grab any new changes you push up to carolynfrunyon/DLTN automatically.

Feel free to address this anyway you want, but here is an idea:
`<xsl:when test="contains(normalize-space(.), 'Chattanooga Women''s Oral Histories')">`

Let me know what you think.

Also, I'm going to change the case of all the files in the repo to make debugging more easy.  It's very difficult to do this in Oxygen in its current state.

**Comment by carolynfrunyon** [comment]
Done, I think.

**Comment by markpbaggett** [comment]
Thanks Carolyn.  Reviewing now. 

What are your 3 new sets? Apologies if I missed that. I assume two of them are: p16877coll21 and p16877coll20.  What's the other?

I'm going to add an issue and p.r. template to help us moving forward.  That will autopopulate some information. Do you think simply opening an issue on the github repo would work for adding new sets?

**Comment by carolynfrunyon** [comment]
I think p16877coll14 is new too.

I guess that would work. I don't really know how to use GitHub. Sorry. I'm probably ruining your life with this pull request.

**Comment by markpbaggett** [comment]
No, this went exactly as it should.  Coll14 isn't new.  I may have accidentally added it a long time ago.  Apologies.

**Comment by carolynfrunyon** [comment]
No worries. All of our sets are fair game :) Thanks for being patient with me.

**Comment by markpbaggett** [comment]
Coll19 isn't there.  Should it be?

**Pull request merged**
